# Generated by Django 4.2.16 on 2025-06-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_cbirthday_alter_customuser_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tel',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='電話'),
        ),
    ]
